local levelDefinitions = {
    {
        activeGames = {"nav"},
        duration = 15,
        nav = {fuckeryRate = 1.2},
        ventgas = {},
        cutsceneDialogue = {
            'After 20 years captaining your own ship, the SPACEPAL, you may have finally run out of luck.',
            'Like usual, you\'re currently trying to deliver supplies across the galaxy ...',
            'and, like usual, you may not get the job done in time.',
            'SPACEPAL is on its last legs and might not make it.',
            'setState:revealBridge',
            'Your crew is tired of not getting paid and may leave mid-trip.',
            'But no matter what, you have to keep the ship moving and complete your deliveries.',
            'If you don\'t, you won\'t have enough money to pay the intergalactic bank and they\'ll repo your beloved pal.',
            'setState:hideBridge',
            'setState:enterIntroWobble',
            'Your flight stabilization system has shut down! I guess that\'s what happens when you\'re too cheap to give your internal systems any TLC (tender loving care, not the seminal 1990s girls group of Waterfalls and CrazySexyCool fame)',
            'setState:revealBridge',
            'setState:highlightNav',
            'Stay on course by clicking the up and down arrows and making sure your ship stays on its path.',
        },
    },
    {
        activeGames = {"nav", "ventgas"},
        duration = 20,
        nav = {fuckeryRate = 0.4},
        ventgas = {gasGrowthRate = 28, wasteGrowthRate = 15, initialGas = 140, initialWaste = 80},
        cutsceneDialogue = {
            'You made it! Unfortunately, your pilot just quit. Good riddance, I say -- turns out the autopilot was doing most of his work anyway.',
            'After initial analysis I\'ve determined that his main job was to maintain the ship\'s atmospheric levels.',
            'You\'ll have to take this on to make sure we get to our next destination. Hold on -- it may be a bumpy ride.',
            'setState:revealBridge',
            'setState:highlightVentgas',
            'Click on the panel screen where the pilot once was and maintain atmospheric levels.',
            'You\'ll have to vent gas to avoid CO2 build up and make sure to get rid of that waste as well. Try not to vent oxygen by accident, or it might get a little hard to breathe in here.'
        },
    },
    {
        activeGames = {"nav", "ventgas", "spinner"},
        duration = 35,
        nav = {fuckeryRate = 0.2},
        ventgas = {gasGrowthRate = 20, wasteGrowthRate = 10},
        spinner = {initialPills = 1, timeToPill = 6, wheelSpeed = 7},
        cutsceneDialogue = {
            'Doctor: "Look Captain, I appreciate you getting us in safely, but during all of that turbulence my life flashed before my eyes ..."',
            'Doctor: "and, to be honest, I\'m not happy with what I saw. Whatever happened to my childhood dream of becoming a folk musician? When did I decide to throw that all away for a doctor?"',
            'Doctor: "I\'ve decided that it\'s time to reclaim my life path - if I\'m not going to get paid, I may as well be doing what I love. The Doctor, out..."',
            'setState:revealBridge',
            'Whoaaaa, we\'re halfway there ... You get the idea.',
            'In the words of the late, great Bob Marley: No Pilot or Doctor, No Cry. To keep the ship in the air, you will need to take on the Doctor\'s main responsibility.',
            'setState:highlightSpinner',
            'Click on the panel the doctor occupied and make sure to get rid of the pills as they enter the tube! Stop the spinner when its corresponding pill color is facing the tube.',
        },
    },
    {
        activeGames = {"nav", "ventgas", "spinner", "misslowcommand"},
        duration = 40,
        nav = {fuckeryRate = 0.1},
        ventgas = {gasGrowthRate = 15, wasteGrowthRate = 8},
        spinner = {initialPills = 0, timeToPill = 9, wheelSpeed = 7},
        misslowcommand = {speed = 50, timeToMissile = 8},
        cutsceneDialogue = {
            'Three deliveries down, one to go... ',
            'I wasn\'t able to fully translate what your Head of Security said right before we docked, so I\'ll just note that it was ... not complimentary.',
            'Suffice it to say she\'s not coming back and you\'ll now need to take on her defense duties to ensure that we arrive at our next destination safely.',
            'setState:revealBridge',
            'setState:highlightMisslowcommand',
            'Protect the ship by activating missile defense and neutralizing incoming missiles. Click on the panel formally occupied by security and click to launch bombs and destroy incoming missiles!',
        },
    },
    {
        activeGames = {"nav", "ventgas", "spinner", "misslowcommand", "plumbing"},
        duration = 75,
        nav = {fuckeryRate = 0.1},
        ventgas = {gasGrowthRate = 8, wasteGrowthRate = 5},
        spinner = {initialPills = 0, timeToPill = 8, wheelSpeed = 7},
        misslowcommand = {speed = 30, timeToMissile = 18},
        plumbing = {fluidRate = 0.23, startBufferFluidRate = 0.08},
        cutsceneDialogue = {
            'Chief Engineer: "Now that there are only two of us, we\'ll be splitting this payload 50/50, right? ... WHAT? What do you mean I still only get 10%?? That\'s it, I\'m out of here."',
            'Well, you\'ve got 99 problems but a crew ain\'t one. It\'s all up to you, now. In addition to your other work, you\'ll need to take on the Chief Engineer\'s main task of maintaining the ship\'s plumbing system.',
            'setState:revealBridge',
            'setState:highlightPlumbing',
            'You\'ll have to move the pipes around to make sure the path connects, and feel free to use the spare pipe.',
        },
    },
    {
        activeGames = {},
        duration = 0,
        ventgas = {},
        cutsceneDialogue = {
            'Congratulations! We\'re almost in range of our last delivery.',
            'Because your whole crew has already left, you don\'t have anything new to do this time around except get SPACEPAL to its final destination.',
            'Thank you for playing!',
        },
    },
}

return levelDefinitions
